#!/bin/bash
#/etc/init.d/zookeeper
RUN_THIS=/bin/su f_etlbroker -c '/home/f_etlbroker/kafka/bin/zookeeper-server-start.sh -daemon /home/f_etlbroker/kafka/config/zookeeper.properties'
DAEMON_PATH=/home/f_etlbroker/kafka/bin/
DAEMON_NAME=zookeeper
# Check that networking is up.
#[ ${NETWORKING} = "no" ] && exit 0

PATH=$PATH:$DAEMON_PATH

# See how we were called.
case "$1" in
  start)
        # Start daemon.
        pid=`ps ax | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
            echo "Zookeeper is already running";
        else
          echo "Starting $DAEMON_NAME";
          #$DAEMON_PATH/zookeeper-server-start.sh -daemon /home/f_etlbroker/kafka/config/zookeeper.properties
          $RUN_THIS
        fi
        ;;
  stop)
        echo "Shutting down $DAEMON_NAME";
        $DAEMON_PATH/zookeeper-server-stop.sh
        ;;
  restart)
        $0 stop
        sleep 2
        $0 start
        ;;
  status)
        pid=`ps ax | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
        dude=`ps aux | grep -i 'org.apache.zookeeper' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          echo "Zookeeper is Running as PID: $pid by user $dude"
        else
          echo "Zookeeper is not Running"
        fi
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
