---
version: '2'
services:
# confluent control center
  control-center:
      image: confluentinc/cp-enterprise-control-center:5.5.0
      hostname: control-center
      container_name: control-center-pja
      ports:
      - "9021:9021"
      environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: '192.168.20.180:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: '192.168.20.180:2181'
      CONTROL_CENTER_CONNECT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: "http://ksqldb-server:8088"
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: "http://localhost:8088"
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

docker run -d \
  --net=host \
  --name=control-center \
  --ulimit nofile=16384:16384 \
  -e CONTROL_CENTER_ZOOKEEPER_CONNECT=192.168.20.180:2181/kafka \
  -e CONTROL_CENTER_BOOTSTRAP_SERVERS=192.168.20.180:9092 \
  -e CONTROL_CENTER_REPLICATION_FACTOR=1 \
  -e CONTROL_CENTER_CONNECT_CLUSTER=http://192.168.20.180:8082 \
  -e CONTROL_CENTER_REST_LISTENERS=http://192.168.20.180:9021 \
  -v /mnt/control-center/data:/var/lib/confluent-control-center \
  confluentinc/cp-enterprise-control-center:5.5.0

...